coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        informational: true
        target: auto # auto compares coverage to the previous base commit
        threshold: 10% # the leniency in hitting the target
        base: auto
    patch:
      default:
        informational: true
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: true
  hide_project_coverage: false
codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
